# Generated by Django 2.1.7 on 2019-04-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subsribe',
            unique_together={('user_from', 'user_to')},
        ),
    ]
